### ISSUE TITLE
Whats the differences between dimcli and cli11

### ISSUE THREAD

**Issue by lenkite** [gknowles/dimcli#14]
Could you please point out what this library offers or how it varies from CLI11 ? https://github.com/CLIUtils/CLI11

**Comment by gknowles** [comment]
The best overview is on the wiki - https://github.com/gknowles/dimcli/wiki

For most programs either should do the job and it's going to come down to which API feels better to you, I haven't seen cli11 before, but from a quick glance the feature differences that I saw are that dimcli:
- encourages defining some options in this file, some in that one, and others over there.
- response files
- more robust parsing of command lines into args (windows, gnu, or glib semantics) - of course most simple programs just use argc/argv[].

And cli11 has:
- configuration files
- windows style options (like "/flags")

There are significant differences in how subcommands are implemented, such as cli11 allowing them to be nested and dimcli treating them more like subprograms.

There are a bunch of other minor feature differences around the edges, but comparing them is also going to be a case of which little things are the most helpful to you.

Having looked I, not surprisingly, like the dimcli syntax better :)
Thanks for your interest!
