### ISSUE TITLE
deps file in the CMAKE_CURRENT_SOURCE_DIR sends cmake server based IDEs into an infinite re-configuring loop

### ISSUE THREAD

**Issue by zeule** [gknowles/dimcli#17]
Moving the file to the binary dir helps.

**Comment by gknowles** [comment]
What is the specific IDE that is failing? I tried VS's open folder which auto detects and runs cmake and it was fine. VSCode also seemed to work, and I think claims to use cmake server, although I didn't try very hard and may not configured it properly.

Moving the deps to bin completely defeats the purpose of the deps file. It is intended to be checked in and for the project to depend on it. It is not written to unless the set of dependent files has changed, so retesting it many times shouldn't result in more than one additional change being detected.

Unless you are referring to something other than CMakeDeps.cmake?

**Comment by zeule** [comment]
It is KDevelop, but as far as I can tell from monitoring the CMake api dir (.cmake/api/v1), it is cmake who generates update events when finishing generating.
